name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Install packages required for the build
      run: |
          sudo apt update
          sudo apt full-upgrade -y
          sudo DEBIAN_FRONTEND=noninteractive apt install -qq devscripts equivs lintian
          mk-build-deps -i -s sudo -t "apt --yes --no-install-recommends"

    - name: Build deb package
      run: dpkg-buildpackage -b -rfakeroot -us -uc

    - name: Install deb package
      run: |
          sudo dpkg -i ../libqgcodeeditor*deb
          sudo apt -y -f install

    - name: Run lintian
      run: lintian ../libqgcodeeditor*deb | lintian-info
